from __future__ import annotations

from sparkbrain.v05.visualizer import build_v05_html


def test_visualizer_is_self_contained_and_uses_confirmatory_results() -> None:
    html = build_v05_html({
        "development_results": [],
        "confirmatory_results": [{"seed": 502, "conditions": {}}],
        "gates": {"A_engineering_stability": True},
    })
    assert "seed 502" not in html  # generated by local JavaScript at runtime
    assert "confirmatory_results" in html
    assert "https://" not in html
    assert "A_engineering_stability" in html
