"""Executable v0.3 design seeds.

These components are intentionally isolated from the accepted v0.2.1 runtime.
They are reference implementations for Codex integration, ablation, and review;
they are not evidence that v0.3 performance or biological fidelity is established.
"""

from .belief import BeliefFieldConfig, PersistentBeliefField
from .coalition import CoalitionGate, CoalitionGateConfig
from .concepts import ConceptFormationConfig, OnlineConceptFormer
from .contracts import (
    BeliefActivation,
    CoalitionState,
    ConceptCandidate,
    EntityBinding,
    EvidenceAuditRow,
    EvidenceContribution,
    EvidenceRecord,
    EvidenceSummary,
    IgnitionDecision,
    OrganAssessment,
    OrganEvidence,
    PerceptualSpark,
    SensorySample,
)
from .entity_binding import (
    E0_GLOBAL,
    E1_ORACLE_ENTITY,
    SlotMetricRow,
    bind_entity,
    derive_binding_id,
    permutation_invariant_slot_metrics,
)
from .evidence import (
    EvidenceLedger,
    EvidenceLedgerConfig,
    derive_evidence_id,
    rejection_envelope_hash,
)
from .evidence_reasoning import (
    G0_HYPOTHESES,
    aggregate_condition_rows,
    decide_g0,
    probability_snapshot,
)
from .evidence_worlds import (
    G0Decision,
    build_evidence_fixture,
    canonical_fixture_json,
    fixture_sha256,
)
from .input_diagnosis import (
    AUTONOMOUS_INPUT_TRACKS,
    DEFAULT_INPUT_TRACK,
    ORACLE_INPUT_TRACK,
    FeatureRecord,
    FrozenPairEvaluator,
    InputFrontend,
    InputRecord,
    LocalCompositionalFrontend,
    PairPrediction,
    StrictSymbolicOracleFrontend,
    WholeHashFrontend,
    create_frontend,
)
from .loop import PerceptualInterpreter, V03ReferenceLoop, V03StepResult
from .organs import OrganGateConfig, assess_organ_candidate
from .revision import (
    RevisionBeliefField,
    RevisionBeliefSnapshot,
    RevisionController,
    RevisionDecision,
    RevisionHeadOutput,
    RevisionObservation,
    RevisionTarget,
    TransitionKind,
)
from .revision_worlds import (
    BELIEF_ORDER,
    C15_E0_GLOBAL,
    C15_E1_ORACLE_ENTITY,
    C15_SCHEMA_VERSION,
    EXPECTED_FULL_FIXTURE_SHA256,
    EXPECTED_SPLIT_MANIFEST_SHA256,
    VARIANT_ORDER,
    WORLD_ORDER,
    FixtureEvidence,
    FixtureVariant,
    RevisionFixtureEpisode,
    SplitManifestRow,
    adapt_fixture_entity_key,
    adapt_fixture_evidence_id,
    add_fixture_evidence,
    assert_frozen_fixture_hashes,
    build_full_fixture,
    build_split_manifest,
    canonical_full_fixture_json,
    canonical_split_manifest_json,
    fixture_document,
    fixture_evidence_to_record,
    fixture_lineage_ids,
    full_fixture_sha256,
    map_attribution_target_ids,
    split_manifest_sha256,
)
from .sensory_field import (
    AdaptiveSensoryField,
    SensoryChannelTrace,
    SensoryFieldConfig,
    SensoryObservation,
    SensoryWorkCounters,
)
from .sensory_worlds import (
    DistractorNoiseWorld,
    GoalTargetWorld,
    HabituationWorld,
    SensoryWorldStep,
    StimulusSpecificityWorld,
    UnexpectedChangeWorld,
)
from .text_frontend import (
    compositional_text_features,
    normalize_text,
    sparse_cosine_similarity,
    symbolic_metadata_features,
    whole_string_hash_features,
)

__all__ = [
    "AdaptiveSensoryField",
    "BeliefActivation",
    "BeliefFieldConfig",
    "BELIEF_ORDER",
    "C15_E0_GLOBAL",
    "C15_E1_ORACLE_ENTITY",
    "C15_SCHEMA_VERSION",
    "CoalitionGate",
    "CoalitionGateConfig",
    "CoalitionState",
    "ConceptCandidate",
    "ConceptFormationConfig",
    "EntityBinding",
    "EvidenceAuditRow",
    "EvidenceContribution",
    "EvidenceLedger",
    "EvidenceLedgerConfig",
    "EvidenceRecord",
    "EvidenceSummary",
    "EXPECTED_FULL_FIXTURE_SHA256",
    "EXPECTED_SPLIT_MANIFEST_SHA256",
    "FixtureEvidence",
    "FixtureVariant",
    "G0Decision",
    "G0_HYPOTHESES",
    "DistractorNoiseWorld",
    "AUTONOMOUS_INPUT_TRACKS",
    "DEFAULT_INPUT_TRACK",
    "ORACLE_INPUT_TRACK",
    "FeatureRecord",
    "FrozenPairEvaluator",
    "InputFrontend",
    "InputRecord",
    "LocalCompositionalFrontend",
    "PairPrediction",
    "StrictSymbolicOracleFrontend",
    "WholeHashFrontend",
    "create_frontend",
    "derive_binding_id",
    "derive_evidence_id",
    "E0_GLOBAL",
    "E1_ORACLE_ENTITY",
    "IgnitionDecision",
    "GoalTargetWorld",
    "HabituationWorld",
    "OnlineConceptFormer",
    "OrganAssessment",
    "OrganEvidence",
    "OrganGateConfig",
    "PerceptualInterpreter",
    "PerceptualSpark",
    "PersistentBeliefField",
    "RevisionBeliefField",
    "RevisionBeliefSnapshot",
    "RevisionController",
    "RevisionDecision",
    "RevisionFixtureEpisode",
    "RevisionHeadOutput",
    "RevisionObservation",
    "RevisionTarget",
    "SensoryFieldConfig",
    "SensoryChannelTrace",
    "SensoryObservation",
    "SensorySample",
    "SensoryWorkCounters",
    "SlotMetricRow",
    "SensoryWorldStep",
    "StimulusSpecificityWorld",
    "SplitManifestRow",
    "TransitionKind",
    "UnexpectedChangeWorld",
    "V03ReferenceLoop",
    "V03StepResult",
    "VARIANT_ORDER",
    "WORLD_ORDER",
    "add_fixture_evidence",
    "adapt_fixture_entity_key",
    "adapt_fixture_evidence_id",
    "assess_organ_candidate",
    "aggregate_condition_rows",
    "assert_frozen_fixture_hashes",
    "bind_entity",
    "build_evidence_fixture",
    "build_full_fixture",
    "build_split_manifest",
    "canonical_fixture_json",
    "canonical_full_fixture_json",
    "canonical_split_manifest_json",
    "compositional_text_features",
    "decide_g0",
    "fixture_sha256",
    "fixture_document",
    "fixture_evidence_to_record",
    "fixture_lineage_ids",
    "full_fixture_sha256",
    "map_attribution_target_ids",
    "normalize_text",
    "permutation_invariant_slot_metrics",
    "probability_snapshot",
    "rejection_envelope_hash",
    "sparse_cosine_similarity",
    "split_manifest_sha256",
    "symbolic_metadata_features",
    "whole_string_hash_features",
]
